server:
  port: 8766

spring:
  application:
    name: service-feign-b

eureka:
  client:
    serviceUrl:
      # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka/，多个地址用,分隔
      defaultZone: http://localhost:8761/eureka/
# 打开断路器
feign:
  hystrix:
    enabled: true